<?php

/**
 * @file
 * Contains contact_manager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contact_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact_manager module.
    case 'help.page.contact_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage you contacts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Adds the default photo field to a contact group.
 *
 * @param \Drupal\contact\ContactGroupInterface $type
 *   A contact group object.
 *
 * @return \Drupal\field\Entity\FieldConfig
 *   A Photo field object.
 */
function contact_group_add_photo_field(ContactGroupInterface $type) {
  // Add or remove the photo field, as needed.
  $field_storage = FieldStorageConfig::loadByName('contact', 'photo');
  $field = FieldConfig::loadByName('contact', $type->id(), 'photo');
  if (empty($field)) {
    $field = FieldConfig::create([
      'field_storage' => $field_storage,
      'bundle' => $type->id(),
      'label' => $label,
      'settings' => [
        'file_directory' => 'contact_photos',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '3MB',
        'max_resolution' => '640x640',
        'min_resolution' => '',
        'alt_field' => false,
        'title_field' => false,
        'alt_field_required' => false,
        'title_field_required' => false,
        'default_image' => [
          'uuid' => NULL,
          'alt' => '',
          'title' => '',
          'width' => NULL,
          'height' => NULL,
        ],
        'handler' => 'default:file',
        'handler_settings' => []
      ],
      'field_type' => 'image',
    ]);
    $field->save();

    // Assign widget settings for the 'default' form mode.
    entity_get_form_display('contact', $type->id(), 'default')
      ->setComponent('photo', [
        'type' => 'image_image',
      ])
      ->save();

    // Assign display settings for the 'default' and 'teaser' view modes.
    entity_get_display('contact', $type->id(), 'default')
      ->setComponent('photo', [
        'label' => 'hidden',
        'type' => 'image',
        'settings'=>[
          'image_style' => 'large'
        ]
      ])
      ->save();
  }

  return $field;
}