<?php
/**
 * @file
 * Contains contact_manager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contact_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact_manager module.
    case 'help.page.contact_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage you contacts') . '</p>';
      return $output;

    default:
  }
}